### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by tejaswigowda** [BehnamZeinali/IMUNet_Android#1]
Can you help?

``` log

> Task :app:compileDebugJavaWithJavac FAILED
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:403: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_3__s10);
                                                         ^
  symbol:   variable behnam_3__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:406: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_5__s10);
                                                         ^
  symbol:   variable behnam_5__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:409: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_11__s10);
                                                         ^
  symbol:   variable behnam_11__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:412: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_12__s10);
                                                         ^
  symbol:   variable behnam_12__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:415: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_13__s10);
                                                         ^
  symbol:   variable behnam_13__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:418: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_26__s10);
                                                         ^
  symbol:   variable behnam_26__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:421: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_28__s10);
                                                         ^
  symbol:   variable behnam_28__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:424: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_29__s10);
                                                         ^
  symbol:   variable behnam_29__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/MainActivity2.java:427: error: cannot find symbol
                is = getResources().openRawResource(R.raw.behnam_29__s10);
                                                         ^
  symbol:   variable behnam_29__s10
  location: class raw
/Users/tejaswigowda/Downloads/IMUNet_Android-master/app/src/main/java/edu/usf/imunet/ComparisonActivity.java:560: error: cannot find symbol
        InputStream is =  getResources().openRawResource(R.raw.data);
                                                              ^
  symbol:   variable data
  location: class raw
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
10 errors



```

**Comment by raikiriww** [comment]
According to the readme. You should download the dataset and put it in the android raw floder. 

> 2- The test part of the [RONIN](https://github.com/Sachini/ronin) for the ResNet18 model using all the proposed models and some samples of the collected dataset has been implemented on Android. Samples can be downloaded [here](https://www.dropbox.com/s/621v5lbf237gxg4/raw.zip?dl=0) and must be put in the raw folder.

**Comment by rorlig** [comment]
the dropbox link is removed ? is there a backup ?

**Comment by raikiriww** [comment]
[behnam_29__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400583/behnam_29__s10.csv)
[data.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400585/data.csv)
[behnam_3__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400575/behnam_3__s10.csv)
[behnam_5__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400577/behnam_5__s10.csv)
[behnam_11__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400578/behnam_11__s10.csv)
[behnam_12__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400579/behnam_12__s10.csv)
[behnam_13__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400580/behnam_13__s10.csv)
[behnam_26__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400581/behnam_26__s10.csv)
[behnam_28__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400582/behnam_28__s10.csv)

@rorlig

**Comment by yasslaclass** [comment]
Nice! 
Thanks @raikiriww

**Comment by BehnamZeinali** [comment]
> [behnam_29__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400583/behnam_29__s10.csv) [data.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400585/data.csv) [behnam_3__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400575/behnam_3__s10.csv) [behnam_5__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400577/behnam_5__s10.csv) [behnam_11__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400578/behnam_11__s10.csv) [behnam_12__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400579/behnam_12__s10.csv) [behnam_13__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400580/behnam_13__s10.csv) [behnam_26__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400581/behnam_26__s10.csv) [behnam_28__s10.csv](https://github.com/BehnamZeinali/IMUNet_Android/files/14400582/behnam_28__s10.csv)
> 
> @rorlig

Thank you for the back up.
